### ISSUE TITLE
calc_token_amount is incorrect in stableswapng views implementation

### ISSUE THREAD

**Issue by bout3fiddy** [curvefi/stableswap-ng#44]
# Description

To replicate:

```
boa.env.fork("https://eth.llamarpc.com")
pool = boa.load_partial('./contracts/CurveStableSwapNG.vy').at('0x383E6b4437b59fff47B619CBA855CA29342A8559')
views = boa.load_partial('./contracts/CurveStableSwapNGViews.vy').at('0xe0B15824862f3222fdFeD99FeBD0f7e0EC26E1FA')
coin_0 = boa.load_partial('./contracts/ERC20Mock.vy').at(pool.coins(0))
amounts = [500000000, 0]

calculated_output = pool.calc_token_amount(amounts, True)

with boa.env.prank('0x7E4B4DC22111B84594d9b7707A8DCFFd793D477A'), boa.env.anchor():
    coin_0.approve(pool.address, 2**256-1)
    actual_output = pool.add_liquidity(amounts, 0)
```
`calculated_output` is `499505730367411984853` whereas `actual_output` is `499594877358336511794`.

# Fix

The issue is caused by the [calc_token_amount in the view contract](https://github.com/curvefi/stableswap-ng/blob/ec972b331da21d919f78943e00bf9398970eca54/contracts/main/CurveStableSwapNGViews.vy#L286):

```
        for i in range(MAX_COINS):
            if i == N_COINS:
                break

            ideal_balance: uint256 = D1 * old_balances[i] / D0
            difference: uint256 = 0
            new_balance: uint256 = new_balances[i]
            if ideal_balance > new_balance:
                difference = ideal_balance - new_balance
            else:
                difference = new_balance - ideal_balance

            xs = old_balances[i] + new_balance
            _dynamic_fee_i = self._dynamic_fee(xs, ys, base_fee, fee_multiplier)
            new_balances[i] -= _dynamic_fee_i * difference / FEE_DENOMINATOR

```

which should be:

```
...
            xs = rates[i] * (old_balances[i] + new_balance) / PRECISION
...
```
To confirm this fix,  please refer to the shared notebook [here](https://try.vyperlang.org/hub/user-redirect/lab/tree/shared/bout3fiddy/calc_token_amount_issue.ipynb).

# Task list

- [x] Fix line on stableswapngviews contract
- [ ] deploy across all chains
- [ ] create dao vote for ethereum implementation
- [ ] execute when proposal passes
